WIDTH = 760
HEIGHT = 760
SQUARE_LENGTH = 40
SQUARE_PIXEL_SIZE = int(WIDTH/SQUARE_LENGTH)
VISUALS = True
FPS = 1000
FOOD_RATE = 10 #1/n chance for i in range(MAX_ADDED_FOOD) per turn
MAX_ADDED_FOOD = 1
MAX_FOOD_VALUE = 1500
MIN_FOOD_VALUE = 500
MAX_TURNS = 10000

MAX_HELD_FOOD = {
    "worker": 100,
    "soldier": 50
}
ANT_HUNGER = 100
ANT_HUNGER_DEGRADE = 1
ANT_HP_DEGRADE_THRESHOLD_HUNGER = 30
ANT_HP_DEGRADE_HUNGER = 1
ANT_HP_HEAL_THRESHOLD_HUNGER = {
    "worker": 20,
    "soldier": 80
}
ANT_HP_HEAL_HUNGER = {
    "worker": 1,
    "soldier": 1
}

SOLDIER_HP = 100
SOLDIER_DMG = 30
WORKER_HP = 25
WORKER_DMG = 10
ANT_HP = {
    "worker": WORKER_HP,
    "soldier": SOLDIER_HP
}
COLONY_HUNGER = 1000
COLONY_HUNGER_DEGRADE = 1
COLONY_HP_DEGRADE_THRESHOLD_HUNGER = 100
COLONY_HP_HEAL_THRESHOLD_HUNGER = 700
COLONY_HP_HEAL_HUNGER = 100
COLONY_HP_DEGRADE_HUNGER = 1
COLONY_HP = 500
COLONY_MAX_EAT = 100
NEW_WORKER_COST = 25 #Worker HP
NEW_SOLDIER_COST = 100 #Soldier HP
DEAD_FOODS = {
    "worker": 10,
    "soldier": 20
}

RED_COLONY_X = 10
RED_COLONY_Y = 30
BLUE_COLONY_X = 30
BLUE_COLONY_Y = 10

QUEEN_PHEROMONE_DURATION = 40
ANT_PHEROMONE_DURATION = 20
QUEEN_PHEROMONES = 5
ANT_PHEROMONES = 5
TOTAL_PHEROMONES = QUEEN_PHEROMONES + ANT_PHEROMONES
PHEROMONE_COLOUR_MULTIPLIER = (1/TOTAL_PHEROMONES) * 255
#Number of pheromones that can visually fit in a horizontal square
PHEROMONES_SQUARE_LENGTH = SQUARE_LENGTH // TOTAL_PHEROMONES
PHEROMONES_PIXEL_WIDTH = 6
PHEROMONE_STATIC_COLOUR = {
    "red": 0,
    "blue": 255
}

############################
########### AI #############
############################

MAX_DEQUE_MEMORY = 100000
#Reward Multipliers
ANT_COL_HP_REWARD_MULTIPLIER = 5
COL_HP_REWARD_MULTIPLIER = 5
ANT_FOOD_REWARD_MULTIPLIER = 1
COL_FOOD_REWARD_MULTIPLIER = 1
MAX_ANT_FOOD_REWARD = 1000
MAX_COL_FOOD_REWARD = 1000

INITIAL_EPSILON = {
    "ant": 80,
    "colony": 80
}
EPSILON_DECAY = {
    "ant": 1,
    "colony": 1
}
GAMMA = {
    "ant": 0.9,
    "colony": 0.9
}

BATCH_SIZE = 100

ANT_INPUT_SIZE = 80
ANT_OUTPUT_SIZE = 10 + ANT_PHEROMONES
ANT_HIDDEN_LAYERS = 5
ANT_HIDDEN_NEURONES = 128
ANT_LR = 0.001

COL_INPUT_SIZE = 70
COL_OUTPUT_SIZE = 3 + QUEEN_PHEROMONES
COL_HIDDEN_LAYERS = 5
COL_HIDDEN_NEURONES = 128
COL_LR = 0.001

TOTAL_EPOCHS = 100