WIDTH = 760
HEIGHT = 760
SQUARE_LENGTH = 40
SQUARE_PIXEL_SIZE = int(WIDTH/SQUARE_LENGTH)
VISUALS = True
FPS = 10
FOOD_RATE = 10 #1/n chance for i in range(MAX_ADDED_FOOD) per turn
MAX_ADDED_FOOD = 1
MAX_FOOD_VALUE = 1500
MIN_FOOD_VALUE = 500

MAX_HELD_FOOD = {
    "worker": 100,
    "soldier": 50
}
ANT_HUNGER = 100
ANT_HUNGER_DEGRADE = 1
ANT_HP_DEGRADE_THRESHOLD_HUNGER = 30
ANT_HP_DEGRADE_HUNGER = 1

SOLDIER_HP = 100
SOLDIER_DMG = 30
WORKER_HP = 25
WORKER_DMG = 10
ANT_HP = {
    "worker": WORKER_HP,
    "soldier": SOLDIER_HP
}
COLONY_HUNGER = 1000
COLONY_HUNGER_DEGRADE = 1
COLONY_HP_DEGRADE_THRESHOLD_HUNGER = 100
COLONY_HP_DEGRADE_HUNGER = 1
COLONY_HP = 500
COLONY_MAX_EAT = 100
NEW_WORKER_COST = 25 #Worker HP
NEW_SOLDIER_COST = 100 #Soldier HP
DEAD_FOODS = {
    "worker": 10,
    "soldier": 20
}

RED_COLONY_X = 10
RED_COLONY_Y = 30
BLUE_COLONY_X = 11
BLUE_COLONY_Y = 30

QUEEN_PHEROMONE_DURATION = 40
ANT_PHEROMONE_DURATION = 20
QUEEN_PHEROMONES = 5
ANT_PHEROMONES = 5
TOTAL_PHEROMONES = QUEEN_PHEROMONES + ANT_PHEROMONES
PHEROMONE_COLOUR_MULTIPLIER = (1/TOTAL_PHEROMONES) * 255
#Number of pheromones that can visually fit in a horizontal square
PHEROMONES_SQUARE_LENGTH = SQUARE_LENGTH // TOTAL_PHEROMONES
PHEROMONES_PIXEL_WIDTH = 6
PHEROMONE_STATIC_COLOUR = {
    "red": 0,
    "blue": 255
}